# Entra ID (Azure AD) Claim Mapping Preset
username: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
email: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
realname: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
firstname: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"
phone: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/telephonenumber"
mobile: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/mobilephone"
jobtitle: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/jobtitle"
country: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/country"
city: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/city"
street: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/streetaddress"
groups: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
